CRITICAL - 2025-09-08 17:16:06 --> ErrorException: Undefined array key "descripcion"
[Method: GET, Route: libros/editar/100061]
in APPPATH\Views\libros\libros_editar.php on line 54.
 1 APPPATH\Views\libros\libros_editar.php(54): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "descripcion"', 'C:\\xampp\\htdocs\\fs2025fs\\codeigniter_biblios\\app\\Views\\libros\\libros_editar.php', 54)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\fs2025fs\\codeigniter_biblios\\app\\Views\\libros\\libros_editar.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('libros/libros_editar', [], true)
 5 APPPATH\Controllers\LibrosController.php(72): view('libros/libros_editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\LibrosController->editarLibro('100061')
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LibrosController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-08 17:24:34 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\app\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
#9 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
#10 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-08 17:24:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '0' for key 'PRIMARY'
[Method: POST, Route: prestamos/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:24:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100002\', \'2025-09-09\', \'2025-09-10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100002\', \'2025-09-09\', \'2025-09-10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:24:34 --> [Caused by] mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100002\', \'2025-09-09\', \'2025-09-10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100002\', \'2025-09-09\', \'2025-09-10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100002\', \'2025-09-09\', \'2025-09-10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-09-08 17:38:49 --> mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY' in C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\app\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
#9 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
#10 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\fs2025fs\codeigniter_biblios\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2025-09-08 17:38:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '0' for key 'PRIMARY'
[Method: POST, Route: prestamos/guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:38:49 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100003\', \'2025-09-09\', \'2025-09-18\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100003\', \'2025-09-09\', \'2025-09-18\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:38:49 --> [Caused by] mysqli_sql_exception: Duplicate entry '0' for key 'PRIMARY'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100003\', \'2025-09-09\', \'2025-09-18\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100003\', \'2025-09-09\', \'2025-09-18\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (\'1001\', \'2013001\', \'100003\', \'2025-09-09\', \'2025-09-18\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `prestamos` (`codigo_empleado`, `carne_alumno`, `codigo_libro`, `fecha_prestamo`, `fecha_devolucion`) VALUES (:codigo_empleado:, :carne_alumno:, :codigo_libro:, :fecha_prestamo:, :fecha_devolucion:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\PrestamosController.php(54): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->guardarPrestamo()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:58:27 --> Error: Call to a member function orderBy() on array
[Method: GET, Route: prestamos]
in APPPATH\Controllers\PrestamosController.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:59:04 --> Error: Call to a member function orderBy() on array
[Method: GET, Route: prestamos]
in APPPATH\Controllers\PrestamosController.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 17:59:29 --> Error: Call to a member function orderBy() on array
[Method: GET, Route: prestamos]
in APPPATH\Controllers\PrestamosController.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 18:00:06 --> Error: Call to a member function orderBy() on array
[Method: GET, Route: prestamos]
in APPPATH\Controllers\PrestamosController.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-09-08 18:00:22 --> Error: Call to a member function orderBy() on array
[Method: GET, Route: prestamos]
in APPPATH\Controllers\PrestamosController.php on line 21.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PrestamosController->index()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PrestamosController))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
